language: python
sudo: false

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: 'nightly'

install:
- pip install coverage flake8 Pygments docutils

script:
- coverage run --source=pydf setup.py test
- flake8 pydf/
- python setup.py install
- tests/check_file_permissions.py
- python -c "import pydf; print(pydf.get_version())"
- if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then python setup.py check -rms; fi

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pypi
  user: samuelcolvin
  password:
    secure: "mA/dvvqWF9yFuti868THNN81NueK9vvNYOokEMRHuabys2c5K1AtYw1SAUjZ/sNdkkgBtXNZB074J8wd3mi8RrsME++0rQmg8vhzsKwI43lE9pvc/jum8nezV7ZKhbT7jziEjv/AAS9s/8L2SJ6DWWaTJf4PDMCNYrAZZ0ySOwQ="
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: 3.5
