language: python
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install coverage codecov flake8

script:
  - coverage run --source=pydf setup.py test
  - flake8 --max-line-length 120 pydf/
  - virtualenv env
  - source env/bin/activate
  - python setup.py install
  - tests/check_file_permissions.py
after_success:
  - codecov
